### ISSUE TITLE
WHERE <ipv4/mac/port/protocol column> LIKE '...' panics (index out of range); IPv6/UUID LIKE silently matches nothing

### ISSUE THREAD

**Issue by derekmwright** [derekmwright/wadjet#497]
## Summary

`WHERE <ipv4_column> LIKE '<pattern>'` crashes the query with an unrecovered `index out of range` panic — process-killer class, since it is NOT a `FatalEvalPanic` and so is re-raised untouched all the way up through `Pipeline.Run`/`ChainDriver.Push`/`DB.Query`, past every layer that exists specifically to convert expected-shape panics into query errors. `WHERE <ipv6_column> LIKE '<pattern>'` does not crash but silently returns 0 rows for every pattern, correct or not. Pre-existing on `main`, not introduced by #484/#485.

## Repro (verified locally)

```go
schema := parquet.Schema{Columns: []parquet.Column{
    {Name: "id", Type: parquet.TypeInt64},
    {Name: "ip", Type: parquet.TypeIPv4, Nullable: true},
    {Name: "ip6", Type: parquet.TypeIPv6, Nullable: true},
}}
// INSERT INTO t (id, ip, ip6) VALUES (1, '10.1.2.3', '2001:db8::1')

db.Query(ctx, `SELECT id FROM t WHERE ip LIKE '10.%'`)   // PANICS
db.Query(ctx, `SELECT id FROM t WHERE ip6 LIKE '2001:%'`) // 0 rows, no error, no match
```

Panic (single-process engine, `wadjet.DB.Query`):

```
panic: runtime error: index out of range [0] with length 0 [recovered, repanicked]
...
github.com/derekmwright/wadjet/internal/engine/batch.(*BytesColumn).Value(...)
	internal/engine/batch/vector.go:226
github.com/derekmwright/wadjet/internal/engine/batch.(*BytesColumn).UnsafeStringValue(...)
	internal/engine/batch/vector.go:256
github.com/derekmwright/wadjet/internal/engine/exec/kernel.ResolveLikeFilterKernel.func1(...)
	internal/engine/exec/kernel/compare.go:861
github.com/derekmwright/wadjet/internal/engine/exec.(*LikeFilter).Execute(...)
	internal/engine/exec/filter.go:722
... (ChainDriver.push → ChainDriver.Push → Pipeline.runParallel → Pipeline.Run → DB.Query)
```

The panic is repanicked at every one of `Pipeline.Run`'s, `ChainDriver.Push`'s, and `DB.Query`'s own `recover()` sites (`internal/engine/exec/pipeline.go`'s `recoverFatalEval`/`RecoverFatalEval`) because it does not implement `FatalEvalPanic` — that mechanism exists ONLY for the one deliberate, controlled panic (#347, a correlated-subquery shape) and re-raises everything else untouched by design. So this reaches the top of the goroutine with nothing left to catch it — in the server binary (not a `recover()`-wrapped test), this takes the process down.

## Root cause

`ResolveLikeFilterKernel` (`internal/engine/exec/kernel/compare.go:842-868`) is built assuming the target vector stores its data in `BytesData` (a string/bytes column) — it unconditionally calls `vec.BytesData.UnsafeStringValue(idx)` with no type check or fallback. But:

- `TypeIPv4`/`TypeMAC` columns store their data in `Int64Data` (`ColRef.Eval`'s int64 fast path, `internal/engine/expr/expr.go:166`, groups these with `TypeInt64`/`TypeTimestamp`/`TypeDuration`) — `BytesData` is empty/nil for these, so `UnsafeStringValue` indexes into a zero-length backing store and panics.
- `TypeIPv6`/`TypeUUID` DO store into `BytesData`, but as their RAW binary form (16 bytes), not the human-readable text the LIKE pattern is written against — so the pattern never matches anything and the query silently returns 0 rows regardless of whether the pattern is a reasonable one.
- `TypeCIDR` is stored as plain text (`parquet/schema.go`) so `LIKE` against it likely works correctly by construction — untested here, worth confirming when this is fixed.
- `TypePort`/`TypeProtocol` are `Int32Data`-backed — the same index-out-of-range panic as IPv4/MAC is expected, not verified here.

This is the same shape of gap `internal/engine/exec/kernel/compare.go`'s `ResolveFilterKernel` (the `=`/`<`/`>` comparison kernel) explicitly dispatches around per-type (`TypeIPv4`/`TypeMAC` → int64 kernels, `TypeIPv6`/`TypeCIDR`/`TypeUUID` → raw-bytes-aware string kernels) — `ResolveLikeFilterKernel` has no equivalent per-type dispatch at all; it is a single, one-size path.

## Suggested direction (not attempted here — filed for the person who picks this up)

`ResolveLikeFilterKernel` needs the same per-type awareness `ResolveFilterKernel` already has: refuse (loud SQL error, not a panic) or render-then-match for `Int64Data`/`Int32Data`-backed network types (IPv4/MAC/PORT/PROTOCOL), and match against the rendered TEXT form (not the raw bytes) for IPv6/UUID. At minimum, the panic needs to stop being a panic — a bounds check that returns "no match" or a proper query error is the immediate safety fix even before the semantic LIKE-on-network-types question is resolved.

## Where this was found

Filed while reviewing #484/#485 (network-typed column fixes) — adjacent territory (`internal/engine/exec/kernel`), not touched by this review's fixes.
